default_language_version:
    # force all unspecified python hooks to run python3
    python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.55.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
